name: Secrets

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dev deps
        run: npm ci

      # --- Fast path for PRs: Secretlint only over changed files
      - name: Secretlint (PR diff, masked)
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          set -euo pipefail
          # База для диффа: SHA из PR или origin/main
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          if [[ -z "$BASE_SHA" ]]; then
            BASE_SHA=$(git rev-parse origin/main || echo "")
          fi

          # Список изменённых файлов; если пусто — выходим корректно
          CHANGED=$(git diff --name-only "${BASE_SHA}...HEAD" | tr '\n' ' ')
          if [[ -z "$CHANGED" ]]; then
            echo "No changed files to scan."
            exit 0
          fi

          echo "Scanning files: $CHANGED"
          npx secretlint --maskSecrets --format stylish $CHANGED

      # --- Deep scan for main: Gitleaks on full repo (with redaction)
      - name: Gitleaks (full repo, redacted)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --redact --config=.gitleaks.toml
